version: '3.8'

services:
  postgres:
    container_name: transcribe_ai
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USE: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: transcribe-ai
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
